//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nodiceweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lost { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
